/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Collector } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {DemographicGenerationInput, Demographics, LLMResponse, MosaicCategory, Responses, SimulationInput, SimulationResult} from "./types"
import type TypeBuilder from "./type_builder"

export class LlmResponseParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  GenerateDemographics(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Demographics[] {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateDemographics",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as Demographics[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateDemographicsBatch(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Demographics[] {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateDemographicsBatch",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as Demographics[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SimulateResponse(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): LLMResponse {
    try {
      return this.runtime.parseLlmResponse(
        "SimulateResponse",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as LLMResponse
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class LlmStreamParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  GenerateDemographics(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (partial_types.Demographics | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateDemographics",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (partial_types.Demographics | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateDemographicsBatch(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (partial_types.Demographics | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateDemographicsBatch",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (partial_types.Demographics | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SimulateResponse(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.LLMResponse {
    try {
      return this.runtime.parseLlmResponse(
        "SimulateResponse",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.LLMResponse
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}