/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  DemographicGenerationInput,  Demographics,  LLMResponse,  MosaicCategory,  Responses,  SimulationInput,  SimulationResult } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface DemographicGenerationInput {
        productDescription?: (string | null)
        targetMarket?: (string | null)
    }
    
    export interface Demographics {
        id?: (string | null)
        age?: (string | null)
        gender?: (string | null)
        interests?: (string | null)[]
        mosaicCategory?: (string | null)
        description?: (string | null)
    }
    
    export interface LLMResponse {
        text?: (string | null)
        choice?: ("ignore" | "followLink" | "followAndBuy" | "followAndSave" | null)
    }
    
    export interface MosaicCategory {
        id?: (string | null)
        name?: (string | null)
        description?: (string | null)
        traits?: (string | null)[]
    }
    
    export interface Responses {
        ignore?: (number | null)
        followLink?: (number | null)
        followAndBuy?: (number | null)
        followAndSave?: (number | null)
    }
    
    export interface SimulationInput {
        demographic?: (partial_types.Demographics | null)
        productDescription?: (string | null)
        tagline?: (string | null)
    }
    
    export interface SimulationResult {
        demographicId?: (string | null)
        responses?: (partial_types.Responses | null)
        totalSims?: (number | null)
    }
    
}